version: "3.8"

services:
  db:
    image: postgres
    container_name: local_db
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: change_me
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - local_db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: changeme@change.me
      PGADMIN_DEFAULT_PASSWORD: change_me
    volumes:
      - pg_admin_data:/var/lib/pgadmin

  redis:
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_ui
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  local_db_data:
  pg_admin_data:
  redis_data: